routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**/
/* FLUXPLAY */
/**/
Route::resource('clients', 'ClientController');
Route::get('search/c/{search_nom}', ['uses' =>'ClientController@search']);
Route::get('search/f/{id}', ['uses' =>'FactureController@search']);
Route::get('dash', function () {
    return view('tst');
});

Route::resource('artisans', 'ArtisanController');

Route::get('search/a/{search_nom}', ['uses' =>'ArtisanController@search']);
//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'DashboardController@index')->name('dashboard');
Route::get('/', 'DashboardController@index')->name('dashboard');

Route::get('/factures', 'FactureController@getFactures')->name('factures');
Route::get('/afactures', 'FactureController@getFacturesArtisan')->name('afactures');
Route::get('/cfactures', 'FactureController@getFacturesClient')->name('cfactures');
Route::get('/recapitulatif', 'FactureController@getRecapitulatifs')->name('recapitulatifs');
Route::post('/recapitulatif', 'FactureController@getRecapitulatifs')->name('recapitulatifs');
Route::get('/pdf/{num_facture}', ['uses' =>'PdfController@read'])->name('pdf');
/* prestations */
Route::get('/prestations', 'PrestationController@index')->name('prestations');
Route::post('/prestations', 'PrestationController@store')->name('prestations.store');
Route::get('/prestations/edit/{id}', 'PrestationController@edit')->name('prestations.edit');
Route::patch('/prestations/update', 'PrestationController@update')->name('prestations.update');
Route::post('/rm/p', 'PrestationController@delete')->name('prestations.delete');
Route::post('/rm/f', 'FactureController@sendFacture')->name('factures.sendfacture');
Route::get('/rm/p/{id}', 'PrestationController@delete2');
// attestations
Route::get('/attestations', 'AttestationController@index')->name('attestations');
Route::get('/pdf/{idClient}/{year}', 'PdfController@readAttestation')->name('attestations.read');
Route::post('/attestations', 'AttestationController@index')->name('attestations.indexWithDate');
Route::post('/attestations/send', 'AttestationController@sendAttestation')->name('attestations.sendmail');
/* -- MAIL --*/
use App\Mail\MailtrapFacture;
use Illuminate\Support\Facades\Mail;
Route::get('/sendmail', function () {


    Mail::to('k3nrdx@example.com')->send(new MailtrapFacture('toto','15855')); 

    return 'A message has been sent to Mailtrap!';

});

Route::get('/sendmail2', 'PrestationController@update');

/**/
/* UPCV */
/**/
Route::get('upcv', function () {
    return view('upcv.home');
});

Route::get('upcv/particuliers', function () {
    return view('upcv.particuliers');
});

Route::get('upcv/professionnels', function () {
    return view('upcv.professionnels');
});

Route::get('upcv/contact', function () {
    return view('upcv.contact');
});

Route::get('upcv/monespace', function () {
    return view('upcv.monespace');
});

Route::any('{query}',
    function() { return redirect('/home'); })
    ->where('query', '.*');

Auth::routes();

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $primaryKey = 'id_client'; // version 5.8
    protected $guarded = ['id_client'];
    public $timestamps = false;

    public function getClientName()
    {
      return $this->civilite." ".$this->nom." ".$this->prenom;
    }

    /* - RELATIONSHIP - */
    public function facture()
    {
      return $this->hasOne('App\Facture','id_client', 'id_client');
    }

    /* - STATIC - */
    public static function getStatusOptions(){
      return array('1' => 'Activé','0' => 'Désactivé');
    }
    public static function getOuiNonOptions(){
      return array('non' => 'Non', 'oui' => 'Oui');
    }
    public static function getCiviliteOptions(){
      return array('M' => 'M.', 'Mlle' => 'Mlle', 'Mme'=>'Mme', 'MetMme'=>'M et Mme');
    }    
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Client;

class ClientController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::where('actif',1)->get();
        return view('clients.index', compact('clients'));
    }

  public function search($search_nom)
  {
    $option="";
    $clients = Client::where('actif',1)->where('nom', 'like', $search_nom . '%')->limit(10)->get();
    foreach($clients as $client)
    {
      $option .= $client->id_client.":".$client->nom." ".$client->prenom."@";
    }
    return $option;
  }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $client = new Client();
      return view('clients.create', compact('client'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
          $this->do_validate($request); 

          $livret   = (!empty($request->get('se_livret')))? $request->get('se_livret') : 0 ;
          $fpapier  = (!empty($request->get('fpapier')))? $request->get('se_livret') : 0 ; 
          $efacture = (!empty($request->get('sz_email')))?1:0;
          $cStatus   = (!empty($request->get('se_status')))?$request->get('se_status'):1;

          $client = new Client([
            'civilite'          =>  $request->get('se_civilite'),
            //'attest_edition'    =>  $request->get('attest_edition'),
            //'attest_lecture'    =>  $request->get('attest_lecture'),
            'nom'               => $request->get('sz_nom'),
            'prenom'            => $request->get('sz_prenom'),
            'adresse1'          => $request->get('sz_adresse1'),
            'adresse2'          => $request->get('sz_adresse2'),
            'ville'             => $request->get('sz_ville'),
            'telephone'         => $request->get('sz_telephone'),
            'cp'                => $request->get('sz_cp'),
            'email'             => $request->get('sz_email'),
            //--
            'livret'            => $livret,
            'fpapier'           => $efacture,
            'b_efacture'        => $efacture,
            'actif'             => $cStatus
          ]);

          if($client->save()){
            $status['text'] = "Felicitation!! le nouveau client ".$client->civilite." ".$client->nom." ".$client->prenom." vient d'etre crée";
            $status['style'] = "success";
          }else{
            $status['text'] = "Une erreur est survenu et le nouveau client n\'a pas pu etre ajouter!";
            $status['style'] = "danger";
          }
          $clients = Client::all();
          return view('clients.index', compact('clients', 'client'), ['status' => $status]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::find($id);
        return view('clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    { 
      $this->do_validate($request); 

        $livret   = (!empty($request->get('se_livret')))? $request->get('se_livret') : 0 ;
        $fpapier  = (!empty($request->get('fpapier')))? $request->get('se_livret') : 0 ; 
        $efacture = (!empty($request->get('sz_email')))?1:0;
        $cStatus   = (!empty($request->get('se_status')))?$request->get('se_status'):1;

        $client = Client::where('id_client',$id)->first();

        $client->civilite       = $request->get('se_civilite');
      //$client->attest_edition = $request->get('attest_edition');
      //$client->attest_lecture = $request->get('attest_lecture');
        $client->nom            = $request->get('sz_nom');
        $client->prenom         = $request->get('sz_prenom');
        $client->adresse1       = $request->get('sz_adresse1');
        $client->adresse2       = $request->get('sz_adresse2');
        $client->ville          = $request->get('sz_ville');
        $client->telephone      = $request->get('sz_telephone');
        $client->cp             = $request->get('sz_cp');
        $client->email          = $request->get('sz_email');
        //--
        //$client->login             = $request->get('sz_login');
        //$client->email          = $request->get('sz_pwd');
        $client->actif          = $cStatus;
        $client->livret         = $livret;
        $client->fpapier        = $fpapier;
        $client->b_efacture     = $efacture;

        if($client->save()){
          $status['text'] = "Felicitation!! le client ".$client->civilite." ".$client->nom." ".$client->prenom." vient d'etre mis a jour";
          $status['style'] = "success";
          $status['nom'] = $client->nom;
        }else{
          $status['text'] = "Une erreur est survenu et le nouveau client n'a pas pu etre ajouter!";
          $status['style'] = "danger";
        }
        $clients = Client::all();
        return view('clients.index', compact('clients', 'client'), ['login'=>'Gregory PEREZ', 'status' => $status]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //$client = Client::find($id);
        $client = Client::where('id_client', $id)->first();
        $client->delete();
   
        return redirect('/clients')->with('success', 'Stock has been deleted Successfully');
    }


    public function do_validate(Request $request){
      $request->validate([
        'se_civilite'=>'required',
        'sz_nom'=> 'required',
        'sz_prenom' => 'required',
        'sz_adresse1' => 'required',
        'sz_cp' => 'required',
        'sz_ville' => 'required'
      ]);
    }
}

resources/views/clients/create.blade.php
@extends('layouts.base')

@section('header')
{{-- algolia --}}
<script src="https://cdn.jsdelivr.net/npm/places.js@1.19.0"></script>
<script>
window.onload = function() {
    var menu = document.getElementById("menu-client");
    menu.className = menu.className + ' ' + 'active';

    var placesAutocomplete = places({
    appId: 'plFWZL4VH8V4',
    apiKey: '96c620770dd1cfa1a062fec065241049',
    container: document.getElementById('sz_adresse1'),
    templates: {
        value: function(suggestion) {
            return suggestion.name;
        }
}
     }).configure({
        type: 'address',
        countries: ['fr']
  });

  placesAutocomplete.on('change', function resultSelected(e) {
    document.getElementById('sz_adresse1').value = e.suggestion.administrative || '';
    document.getElementById('sz_ville').value = e.suggestion.city || '';
    document.getElementById('sz_cp').value = e.suggestion.postcode || '';
  });

};
</script>
<style>
.uper {
    margin-top: 40px;
}
</style>
<!-- DataTables -->
<link href="/vendor/xadmino/Admin/assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet"
    type="text/css" />
<link href="/vendor/xadmino/Admin/assets/plugins/datatables/responsive.bootstrap.min.css" rel="stylesheet"
    type="text/css" />

<link href="/vendor/xadmino/Admin/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/vendor/xadmino/Admin/assets/css/icons.css" rel="stylesheet" type="text/css">
<link href="/vendor/xadmino/Admin/assets/css/style.css" rel="stylesheet" type="text/css">
@endsection

@section('footer')
<!-- jQuery  -->
<script src="/vendor/xadmino/Admin/assets/js/jquery.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/bootstrap.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/modernizr.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/detect.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/fastclick.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.slimscroll.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.blockUI.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/waves.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/wow.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.nicescroll.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.scrollTo.min.js"></script>

<!-- Datatables-->
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/vfs_fonts.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/buttons.html5.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/buttons.print.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/responsive.bootstrap.min.js"></script>

<!-- Datatable init js -->
<script src="/vendor/xadmino/Admin/assets/pages/datatables.init.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/app.js"></script>
@endsection

@section('content')


<input type="search" id="address-input" placeholder="Where are we going?" />



<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-header-title">
                        <h4 class="pull-left page-title">Bienvenue sur la page des clients</h4>
                        <ol class="breadcrumb pull-right">
                            <li><a href="/public/clients">Retour á la liste des clients</a></li>
                            <li class="active">FluXplaY</li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

            <div class="col-sm-12">
                <div class="panel panel-color panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Creer un nouveau client</h3>
                    </div>
                    
                    {{-- form status row  --}}
                    @include('subviews.formstatus')

                        <form method="post" class="form-horizontal" action="{{ route('clients.store') }}">
                        {{ csrf_field() }}
                            <div class="modal-body">
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="se_civilite">Civilité </label>
                                    <div class="col-md-10">
                                        <select class="form-control" name="se_civilite" id="se_civilite">
                                            <option value="M">M.</option>
                                            <option value="Mlle">Mlle</option>
                                            <option value="Mme">Mme</option>
                                            <option value="MetMme">M et Mme</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="sz_nom">Nom:</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" name="sz_nom" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="sz_prenom">Prenom :</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" name="sz_prenom" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="sz_adresse1">Adresse :</label>
                                    <div class="col-md-10">
                                        <input type="search" id="sz_adresse1" name="sz_adresse1" class="form-control" placeholder="Quel est votre adresse?" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="sz_adresse2">Complement :</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" name="sz_adresse2" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="sz_ville">Ville:</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="sz_ville" name="sz_ville" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="sz_cp">CP:</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="sz_cp" name="sz_cp" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="sz_telephone">Telephone :</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" name="sz_telephone" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="sz_email">Email:</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" name="sz_email" />
                                    </div>
                                </div>
                                {{-- <div class="form-group">
                                    <label class="col-md-2 control-label" for="se_livret">Livret d'accueil </label>
                                    <div class="col-md-10">
                                        <select class="form-control" name="se_livret" id="se_livret">
                                            @foreach($client->getOuiNonOptions() as $key => $value)
                                            <option value="{{ $key }}">{{ $value }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="se_fpapier">Facture papier </label>
                                    <div class="col-md-10">
                                        <select class="form-control" name="se_fpapier" id="se_fpapier">
                                            @foreach($client->getOuiNonOptions() as $key => $value)
                                            <option value="{{ $key }}">{{ $value }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="se_efacture">Facture email </label>
                                    <div class="col-md-10">
                                        <select class="form-control" name="se_efacture" id="se_efacture"
                                            value={{ $client->b_efacture }}>
                                            @foreach($client->getOuiNonOptions() as $key => $value)
                                            <option value="{{ $key }}">{{ $value }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-2 control-label" for="se_status">Status </label>
                                    <div class="col-md-10">
                                        <select class="form-control" name="se_status" id="se_status"
                                            value={{ $client->actif }}>
                                            @foreach($client->getStatusOptions() as $key => $value)
                                            <option value="{{ $key }}">{{ $value }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div> --}}
                                <button type="submit" class="btn btn-primary">Creér un nouveau client</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div> <!-- container -->
</div> <!-- content -->
<footer class="footer">
    2010 - 2020 © FluXplaY.
</footer>

</div>
@endsection

resources/views/clients/dashboard.blade.php
@extends('layouts.base')

@section('header')
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

    <!-- DataTables -->
    <link href="/vendor/xadmino/Admin/assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <link href="/vendor/xadmino/Admin/assets/plugins/datatables/responsive.bootstrap.min.css" rel="stylesheet" type="text/css" />

    <link href="/vendor/xadmino/Admin/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/vendor/xadmino/Admin/assets/css/icons.css" rel="stylesheet" type="text/css">
    <link href="/vendor/xadmino/Admin/assets/css/style.css" rel="stylesheet" type="text/css">

<script>
window.onload = function() 
{
    var menu = document.getElementById("menu-dashboard");
    menu.className = menu.className + ' ' + 'active' ;
}
</script>
@endsection

@section('content')
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

<!-- body -->
<!-- 1er ligne -->
<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-primary text-center">
            <div class="panel-heading">
                <h4 class="panel-title">Nb total de facture</h4>
            </div>
            <div class="panel-body">
                <h2 class=""><b>25</b></h2>
                <p class="text-muted"><b>25</b> facture depuis le debut de l'inscription.</p>
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="panel panel-primary text-center">
            <div class="panel-heading">
                <h4 class="panel-title">Nb facture cette année</h4>
            </div>
            <div class="panel-body">
                <h2 class=""><b>12</b></h2>
                <p class="text-muted"><b>12</b> factures depuis janvier cette année.</p>
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="panel panel-primary text-center">
            <div class="panel-heading">
                <h4 class="panel-title">Montant de votre derniere facture</h4>
            </div>
            <div class="panel-body">
                <h3 class=""><b>2779.7 €</b></h3>
                <p class="text-muted">Facture de <b>jardinage</b> editer le 05/08/2020</p>
            </div>
        </div>
    </div>
</div>

<!-- 2eme ligne -->
<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-fill panel-upcv">
            <div class="panel-heading">
                <h3 class="panel-title">Consulter vos Factures</h3>
            </div>
            <div class="panel-body">
                <p>Consulter en tout temps vos factures des années precedantes. </p>
                <a href="/public/factures" class="btn btn-dark btn-block waves-effect waves-light" role="button">Mes factures</a>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-fill panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Consulter vos Attestations fiscales</h3>
            </div>
            <div class="panel-body">
                <p>Consulter en tout temps vos factures des années precedantes. </p>
                <a href="/public/attestation" class="btn btn-dark btn-block waves-effect waves-light" role="button">Mes attestations</a>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-fill panel-upcv-light">
            <div class="panel-heading">
            <h3 class="panel-title">Consulter le récapitulatif</h3>
            </div>
            <div class="panel-body">
                <p>Consulter en tout temps vos factures des années precedantes. </p>
                <a href="/public/attestation" class="btn btn-dark btn-block waves-effect waves-light" role="button">Mon récapitulatif</a>
            </div>
        </div>
    </div>
</div>

        </div> <!-- container -->
    </div> <!-- content -->
    <footer class="footer">
        2016 - 2020 © FluXplaY.
    </footer>

</div>
@endsection


@section('footer')
<!-- jQuery  -->
<script src="/vendor/xadmino/Admin/assets/js/jquery.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/bootstrap.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/modernizr.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/detect.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/fastclick.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.slimscroll.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.blockUI.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/waves.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/wow.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.nicescroll.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.scrollTo.min.js"></script>

<!-- Datatables-->
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/vfs_fonts.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/buttons.html5.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/buttons.print.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/responsive.bootstrap.min.js"></script>

<!-- Datatable init js -->
<script src="/vendor/xadmino/Admin/assets/pages/datatables.init.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/app.js"></script>

@endsection