routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**/
/* FLUXPLAY */
/**/
Route::resource('clients', 'ClientController');
Route::get('search/c/{search_nom}', ['uses' =>'ClientController@search']);
Route::get('search/f/{id}', ['uses' =>'FactureController@search']);
Route::get('dash', function () {
    return view('tst');
});

Route::resource('artisans', 'ArtisanController');

Route::get('search/a/{search_nom}', ['uses' =>'ArtisanController@search']);
//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'DashboardController@index')->name('dashboard');
Route::get('/', 'DashboardController@index')->name('dashboard');

Route::get('/factures', 'FactureController@getFactures')->name('factures');
Route::get('/afactures', 'FactureController@getFacturesArtisan')->name('afactures');
Route::get('/cfactures', 'FactureController@getFacturesClient')->name('cfactures');
Route::get('/recapitulatif', 'FactureController@getRecapitulatifs')->name('recapitulatifs');
Route::post('/recapitulatif', 'FactureController@getRecapitulatifs')->name('recapitulatifs');
Route::get('/pdf/{num_facture}', ['uses' =>'PdfController@read'])->name('pdf');
/* prestations */
Route::get('/prestations', 'PrestationController@index')->name('prestations');
Route::post('/prestations', 'PrestationController@store')->name('prestations.store');
Route::get('/prestations/edit/{id}', 'PrestationController@edit')->name('prestations.edit');
Route::patch('/prestations/update', 'PrestationController@update')->name('prestations.update');
Route::post('/rm/p', 'PrestationController@delete')->name('prestations.delete');
Route::post('/rm/f', 'FactureController@sendFacture')->name('factures.sendfacture');
Route::get('/rm/p/{id}', 'PrestationController@delete2');
// attestations
Route::get('/attestations', 'AttestationController@index')->name('attestations');
Route::get('/pdf/{idClient}/{year}', 'PdfController@readAttestation')->name('attestations.read');
Route::post('/attestations', 'AttestationController@index')->name('attestations.indexWithDate');
Route::post('/attestations/send', 'AttestationController@sendAttestation')->name('attestations.sendmail');
/* -- MAIL --*/
use App\Mail\MailtrapFacture;
use Illuminate\Support\Facades\Mail;
Route::get('/sendmail', function () {


    Mail::to('k3nrdx@example.com')->send(new MailtrapFacture('toto','15855')); 

    return 'A message has been sent to Mailtrap!';

});

Route::get('/sendmail2', 'PrestationController@update');

/**/
/* UPCV */
/**/
Route::get('upcv', function () {
    return view('upcv.home');
});

Route::get('upcv/particuliers', function () {
    return view('upcv.particuliers');
});

Route::get('upcv/professionnels', function () {
    return view('upcv.professionnels');
});

Route::get('upcv/contact', function () {
    return view('upcv.contact');
});

Route::get('upcv/monespace', function () {
    return view('upcv.monespace');
});

Route::any('{query}',
    function() { return redirect('/home'); })
    ->where('query', '.*');

Auth::routes();

app/Artisan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Artisan extends Model
{
    protected $primaryKey = 'id_artisans'; // version 5.8
    protected $guarded = [];
    public $timestamps = false;

// +------------------------------------------------------+
// +----------------RELASHIONSHIP-------------------------+
// +------------------------------------------------------+
    public function facture(){
        return $this->hasOne('App\Facture','id_artisans', 'id_artisans');
    }

// +-------------------------------------------------+
// +---------------- STATIC -------------------------+
// +-------------------------------------------------+
    public static function getSecNaturesArray($secNatures)
    {
        if(!empty($secNatures)){
            return explode(',', $secNatures);
        }else{ return array(); }
    }
    public static function getTvaOptions()
    {
        return array(
         '0.0'=>'0%',
        '20.0'=>'20%');
    }

    public static function getTauxOptions()
    {
        return array(
        '3.0'       =>'3.0%',
        '5.0'       =>'5.0%',
        '6.0'       =>'6.0%',
        '7.0'       =>'7.0%',
        '8.0'       =>'8.0%',
        '9.0'       =>'9.0%',
        '10.0'      =>'10.0%',
        '11.0'      =>'11.0%',
        '12.0'      =>'12.0%',
        '15.0'      =>'15.0%',
        '18.0'      =>'18.0%',
        '20.0'      =>'20.0%',
        '25.0'      =>'25.0%',
        '30.0'      =>'30.0%'
    );
    }

    public static function getTypeSociete()
    {
        return array(
            'sarl'=>'SARL',
            'eiae'=>'EI / AE',
            'eurl'=>'EURL', 
            'sas'=>'SAS');
    }
    public static function getStatusOptions(){
        
        return array('1' => 'Activé','0' => 'Désactivé');
    }
    public static function getStatusLabel($value=0){
        $tab = array('1' => 'Activé','0' => 'Désactivé');
        if($value==1)
        {
            return $tab[1];
        }else{
            return $tab[0];
        } 
    }

}

app/Http/Controllers/ArtisanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Artisan;

class ArtisanController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $artisans = Artisan::all();
        return view('artisans.index', compact('artisans'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('artisans.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->check($request);

        $artisan = new Artisan([
            'type'           =>  $request->get('se_type'),
            'nom'            =>  $request->get('sz_nom'),
            'contact'        => $request->get('sz_contact'),
            'adresse'        => $request->get('sz_adresse'),
            'cp'             => $request->get('sz_cp'),
            'ville'          => $request->get('sz_ville'),
            'siret'          => $request->get('sz_siret'),
            'tva'            => $request->get('se_tva'),
            'nature'         => $request->get('pri_nature'),
            'nature_sec'     => implode(",", $request->get('sec_nature')),
            'taux'           => $request->get('se_taux'),
            'telephone'      => $request->get('sz_tel'),
            'mail'           => $request->get('sz_email'),
            'adhesion'       => date("Y-m-d"),
            'logo'           => $request->get('sz_logo'),
            'facebook'       => $request->get('sz_facebook'),
            'linkedin'       => $request->get('sz_linkedin'),
            'siteweb'        => $request->get('sz_siteweb'),
            'actif'          => 1
        ]);

        if($artisan->save()){
            $status['text'] = "Felicitation!! l'artisan ".$artisan->nom." vient d'etre crée";
            $status['style'] = "success";
            $status['nom'] = $artisan->nom;
        }else{
            $status['text'] = "Une erreur est survenu et le nouvel artisan n\'a pas pu etre ajouté!";
            $status['style'] = "danger";
        }
        $artisans = Artisan::all();
        return view('artisans.index', compact('artisans', 'artisan'), ['login'=>'Gregory PEREZ', 'status' => $status]);
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $artisan = Artisan::find($id);
        return view('artisans.edit', compact('artisan'));
    }

    public function search($search_nom)
    {
        $option="";
        $artisans = Artisan::where('nom', 'like', $search_nom . '%')->limit(10)->get();
        foreach($artisans as $artisan)
        {
            $option .= $artisan->id_artisans.":".$artisan->tva.":".$artisan->taux.":".$artisan->nom."@";
        }
        return $option;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->check($request);

        $artisan = Artisan::find($id);

        if(!empty($artisan->id_artisans) && $artisan->id_artisans>0){

            $artisan->type         = $request->get('se_type');
            $artisan->nom          = $request->get('sz_nom');
            $artisan->contact      = $request->get('sz_contact');
            $artisan->adresse      = $request->get('sz_adresse');
            $artisan->cp           = $request->get('sz_cp');
            $artisan->ville        = $request->get('sz_ville');
            $artisan->siret        = $request->get('sz_siret');
            $artisan->tva          = $request->get('se_tva');
            $artisan->telephone    = $request->get('sz_tel');
            $artisan->mail         = $request->get('sz_email');
            $artisan->nature       = $request->get('pri_nature');
            $artisan->nature_sec   = implode(",", $request->get('sec_nature'));
            $artisan->taux        = $request->get('se_taux');
            $artisan->siteweb     = $request->get('sz_siteweb');
            $artisan->facebook    = $request->get('sz_facebook');
            $artisan->linkedin    = $request->get('sz_linkedin');
            $artisan->logo        = $request->get('sz_logo');
            $artisan->actif       = $request->get('se_status');
            $artisan->save();
        }

        $artisans = Artisan::all();
        return view('artisans.index', compact('artisans'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function check(Request $request)
    {
        $request->validate([
            'se_type'=>'required',
            'sz_nom'=>'required',
            'sz_siret'=> 'required',
            'se_tva' => 'required',
            'se_taux' => 'required',
            'sz_adresse' => 'required',
            'sz_cp' => 'required',
            'sz_ville' => 'required',
            'sz_contact' => 'required',
            'pri_nature' => 'required'
        ],[
            'se_type.required'=>'Vous devez fournir un type de sociéte valide.',
            'sz_nom.required'=>'Vous devez fournir un nom de sociéte valide.',
            'sz_siret.required'=>'Vous devez fournir un numéro de SIRET valide.',
            'se_tva.required'=>'Une TVA valide doit etre appliquée.',
            'se_taux.required'=>'Un taux valide doit etre appliquée.',
            'sz_adresse.required'=>'Vous devez fournir une adresse de sociéte.',
            'sz_cp.required'=>'Vous devez fournir un code postal á la sociéte.',
            'sz_ville.required'=>'Vous devez fournir une ville valide á la sociéte.',
            'sz_contact.required'=>'Vous devez fournir un contact pour cette sociéte.',
            'pri_nature.required'=>'Au moins une nature de travaux doit etre appliqué.'
        ]);
    }

}

resources/views/artisans/create.blade.php
@extends('layouts.base')

 {{-- Using for static function --}}
  <?php use App\Prestation; ?>
  <?php use App\Artisan; ?>


@section('header')
<script>
window.onload = function() {
    var menu = document.getElementById("menu-artisan");
    menu.className = menu.className + ' ' + 'active';
};
</script>
<style>
.uper {
    margin-top: 40px;
}
</style>
<!-- DataTables -->
<link href="/vendor/xadmino/Admin/assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet"
    type="text/css" />
<link href="/vendor/xadmino/Admin/assets/plugins/datatables/responsive.bootstrap.min.css" rel="stylesheet"
    type="text/css" />

<link href="/vendor/xadmino/Admin/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/vendor/xadmino/Admin/assets/css/icons.css" rel="stylesheet" type="text/css">
<link href="/vendor/xadmino/Admin/assets/css/style.css" rel="stylesheet" type="text/css">
@endsection

@section('footer')
<!-- jQuery  -->
<script src="/vendor/xadmino/Admin/assets/js/jquery.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/bootstrap.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/modernizr.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/detect.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/fastclick.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.slimscroll.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.blockUI.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/waves.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/wow.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.nicescroll.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.scrollTo.min.js"></script>

<!-- Datatables-->
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/vfs_fonts.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/buttons.html5.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/buttons.print.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/responsive.bootstrap.min.js"></script>

<!-- Datatable init js -->
<script src="/vendor/xadmino/Admin/assets/pages/datatables.init.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/app.js"></script>
@endsection

@section('content')
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-header-title">
                        <h4 class="pull-left page-title">Bienvenue sur la page des adhérents</h4>
                        <ol class="breadcrumb pull-right">
                            <li><a href="/public/artisans">Retour á la liste des adhérents</a></li>
                            <li class="active">FluXplaY</li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>

            <div class="col-sm-12">
                <div class="panel panel-color panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Creer un nouvel adhérent</h3>
                    </div>
                    
                    {{-- form status row  --}}
                    @include('subviews.formstatus')
                        <form method="post" class="form-horizontal" action="{{ route('artisans.store') }}">
                            {{ csrf_field() }}
                        <div class="modal-body">
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="se_type">Type</label>
                                <div class="col-md-10">
                                    <select class="form-control" name="se_type" id="se_type">
                                        @foreach(Artisan::getTypeSociete() as $key => $value)
                                            <option value="{{ $key }}">{{ $value }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_nom">Societé</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_nom"  />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_contact">Dirigeant</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_contact"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_adresse">Adresse</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_adresse"   />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_cp">CP</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_cp"   />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_ville">Ville</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_ville"   />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_siret">Siret</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_siret"   />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="se_tva">Tva</label>
                                <div class="col-md-10">
                                    <select class="form-control" name="se_tva" id="se_tva">
                                        @foreach(Artisan::getTvaOptions() as $key => $value)
                                        <option value="{{ $key }}" >{{ $value }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="pri_nature">Nature principale</label>
                                <div class="col-md-10">
                                    <select class="form-control" name="pri_nature" id="pri_nature">
                                        @foreach(Prestation::getNatureOptions() as $key => $value)
                                            <option value="{{ $key }}">{{ $value }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sec_nature">Natures secondnaires</label>
                                <div class="col-md-10">
                                    <select multiple size="5" class="form-control" name="sec_nature[]" id="sec_nature">
                                        @foreach(Prestation::getNatureOptions() as $key => $value)
                                        <option value="{{ $key }}">{{ $value }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="se_taux">Taux</label>
                                <div class="col-md-10">
                                    <select class="form-control" name="se_taux" id="se_taux">
                                        @foreach(Artisan::getTauxOptions() as $key => $value)
                                        <option value="{{ $key }}" >{{ $value }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_tel">Telephone</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_tel" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_email">Email</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_email" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_siteweb">Site Web</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_siteweb" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_facebook">Facebook</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_facebook" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_linkedin">Linkedin</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_linkedin" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-2 control-label" for="sz_logo">Logo</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" name="sz_logo" />
                                </div>
                            </div>
                            {{-- <div class="form-group">
                                <label class="col-md-2 control-label" for="se_status">Status </label>
                                <div class="col-md-10">
                                    <select class="form-control" name="se_status" id="se_status">
                                        @foreach(Artisan::getStatusOptions() as $key => $value)
                                        <option value="{{ $key }}" >{{ $value }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div> --}}
                            <button type="submit" class="btn btn-primary">Ajouter</button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>



        </div>
    </div>


</div> <!-- container -->
</div> <!-- content -->
<footer class="footer">
    2016 - 2020 © FluXplaY.
</footer>

</div>
@endsection

resources/views/artisans/dashboard.blade.php
@extends('layouts.base')

@section('header')
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

    <!-- DataTables -->
    <link href="/vendor/xadmino/Admin/assets/plugins/datatables/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <link href="/vendor/xadmino/Admin/assets/plugins/datatables/responsive.bootstrap.min.css" rel="stylesheet" type="text/css" />

    <link href="/vendor/xadmino/Admin/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/vendor/xadmino/Admin/assets/css/icons.css" rel="stylesheet" type="text/css">
    <link href="/vendor/xadmino/Admin/assets/css/style.css" rel="stylesheet" type="text/css">

<script>
window.onload = function() 
{
    var menu = document.getElementById("menu-dashboard");
    menu.className = menu.className + ' ' + 'active' ;
}
</script>
@endsection

@section('content')
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

                    <!-- body -->

<div class="row">
    <div class="col-lg-4">
        <div class="panel panel-fill panel-upcv">
            <div class="panel-heading">
                <h3 class="panel-title">Consulter vos Factures</h3>
            </div>
            <div class="panel-body">
                <p>Consulter en tout temps vos factures des années precedantes. </p>
                <a href="/public/recapitulatif" class="btn btn-dark btn-block waves-effect waves-light" role="button">Mes factures</a>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-fill panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Consulter vos Attestations fiscales</h3>
            </div>
            <div class="panel-body">
                <p>Consulter en tout temps vos factures des années precedantes. </p>
                <a href="/public/recapitulatif" class="btn btn-dark btn-block waves-effect waves-light" role="button">Mes attestations</a>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="panel panel-fill panel-upcv-light">
            <div class="panel-heading">
            <h3 class="panel-title">Consulter le récapitulatif</h3>
            </div>
            <div class="panel-body">
                <p>Consulter en tout temps vos factures des années precedantes. </p>
                <a href="/public/recapitulatif" class="btn btn-dark btn-block waves-effect waves-light" role="button">Mon récapitulatif</a>
            </div>
        </div>
    </div>
</div>



        </div> <!-- container -->
    </div> <!-- content -->
    <footer class="footer">
        2016 - 2020 © FluXplaY.
    </footer>

</div>
@endsection


@section('footer')
<!-- jQuery  -->
<script src="/vendor/xadmino/Admin/assets/js/jquery.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/bootstrap.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/modernizr.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/detect.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/fastclick.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.slimscroll.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.blockUI.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/waves.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/wow.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.nicescroll.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/jquery.scrollTo.min.js"></script>

<!-- Datatables-->
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/dataTables.bootstrap.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/vfs_fonts.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/buttons.html5.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/buttons.print.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/dataTables.responsive.min.js"></script>
<script src="/vendor/xadmino/Admin/assets/plugins/datatables/responsive.bootstrap.min.js"></script>

<!-- Datatable init js -->
<script src="/vendor/xadmino/Admin/assets/pages/datatables.init.js"></script>
<script src="/vendor/xadmino/Admin/assets/js/app.js"></script>

@endsection